name: Deploy Environment Action

on: 
  push:
    branches:
      - "ci-actions-testing"

env:
  K8S_MANIFEST_DIR: deploy/k8s
  GO_VERSION: 1.17.2

jobs:
  elastic-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          # version: "0.12.0"
          cluster_name: kind-mono
          config: .github/kind-config.yaml
      
      - uses: azure/setup-helm@v1
        id: install

      - name: Docker build Cloudbeat
        run: |
          GOOS=linux go build -v && docker build -t cloudbeat .  && kind load docker-image cloudbeat:latest --name kind-mono
      
      - name: Docker build tests-container
        run: |
          cd tests; docker build -t cloudbeat-test:0.0.6 . && kind load docker-image cloudbeat-test:0.0.6 --name kind-mono
      
      - name: Deploy tests Helm chart
        run: |
          helm upgrade --wait --install --values tests/deploy/k8s-cloudbeat-tests/k8s-values.yaml --namespace kube-system --kube-context kind-kind-mono cloudbeat-tests  tests/deploy/k8s-cloudbeat-tests/ 

      - name: Helm Test
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm test cloudbeat-tests --kube-context kind-kind-mono --logs
